[profile.default]
solc = "0.8.18"
libs = ["lib"]
allow_paths = ["../../node_modules"]
extra_output = [
  "abi",
  "evm.bytecode",
  "evm.deployedBytecode",
  "evm.methodIdentifiers",
  "storageLayout",
]
extra-output-files = ["abi"]
ffi = true

fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 80

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
mumbai = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }

[rpc_endpoints]
polygon = "${INFURA_POLYGON_MAINNET_RPC_URL}/${INFURA_POLYGON_MAINNET_API_KEY}"
mumbai = "${INFURA_POLYGON_MUMBAI_RPC_URL}/${INFURA_POLYGON_MUMBAI_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
